# Grading policy

**Rubrics** will be made available prior to most major assignments.  On-time completion of all items of the rubric following the norms of scientific writing (formatting, tone, focus, and to some extent grammar and spelling) will result in a score of **87%** of the points for the assignment.  

Additional points can be earned up to the maximum possible by submitting work that displays research, polish, professional quality and/or effort beyond what is outlined in the rubric.  Similarly, work that displays significant *improvement* in effort or writing skills may earn additional points.  

## Tips for MEETING the “B” standard on assignments

* Turn in the assignment on time
* Double check that you’ve met all the requirements for the assignment; if one is available use the rubric as a check-off list.
* Re-read your assignment one last time before submitting to check for spelling, grammar, and formatting mistakes.
* Make sure any and all references, citations, and species names are formatted correctly.

## Tips for EXCEEDINBG the “B” standard on assignments

* Finish the assignment a day early, then re-read it before submitting it.
* Have a friend, labmate or family member read it and make revisions based on their feedback
* Consider your choice of references you’ve used.  Have you selected the best thing to cite for a particular statement?  Is there something more recent?  Should you cite the primary literature instead of a review?  Should you cite a review instead of the primary literature?
* Are there any run-on sentences?  Should they be split into two sentences?
* Are your sentences as direct and clear as possible?  Have you unnecessarily used commas, prepositional phrases, or put things into parentheses (Honestly, you probably should never put stuff in parentheses unless it's for a *very* specific purpose, like statistics).
