# Course overview

The goal of Biosci 1010 is to develop your skill understanding and communicating biology.  Over the course of the semester you will work on understanding an area of cutting-edge biological research and then
1. Writing about it to audiences with different scientific backgrounds  
1. Summarizing key ideas graphically
1. Giving an oral presentation on the topic

## Biological Focus

The biological focus of this course is the evolution of **local adaptations** in humans.  Humans and chimpanzees have almost identical genomes, but the small amount of variation - perhaps as little as 2% - results in adaptations to vastly different conditions.  Chimpanzees are highly intelligent, social animals that use tools and have culture, but are restricted to living in tropical forests and savannas in West and Central Africa.  Human anatomical and cognitive adaptions have allowed us to colonize almost the entire planet and fabricate sophisticated technology and communicate in a variety of ways.

If you compare the genomes of two humans, you will have to work really hard to find genetic differences.  Differences exist, and we often learn about how a person's particular genetic inheritance impacts phenotypic features such as their eye color, skin pigmentation or susceptibility to certain diseases.

Since the sequencing of the human genome and the advent of next-generation sequencing, we are now able to explore the phenotypic and genetic diversity of humans to understand how subtle differences can impact factors such as our health.  Additional, the invention of powerful bioinformatics tools allow us to explore the origins and genetic history phenotypic and genetic differences.  For example, there is now strong evidence that humans have convergent adapted to living at high elevations where oxygen levels negatively impact human physiology.  This has occurred in three geographically and culturally distinct populations: Ethiopia, Tibet, and Andean South America.  While the large-scale phenotype is the same - the ability to thrive at high elevations - the physiology and genetic bases are somewhat unique to each population.

While genomics and bioinformatics are revealing many interesting stories chronicled in the genomes of different population around, they are not sufficient to tell the whole story.  Genomic data can identify if a gene appears to have undergone natural selection and the type of selection (negative or positive, directional or stabilizing, etc).  Genomic data alone however cannot demonstrate that a particular gene and its biochemical protein are linked to a particular phenotype - this requires the creativity and skill of laboratory biologists to design **functional assays** to show how different mutations results in different cellular, physiological, and whole-organism phenotypes.

## The arc of this course

The goal of this course is for you to conduct in-depth research on a gene that is 

* Hypothesized to have undergone recent natural selection
* Has had some form of functional assay or other rigorous analysis done to determine the phenotypic effects of mutations.

You will then communicate your findings to me, your classmates, and other members of the Pitt Biosci community.

This tasks have 2 major parts:

1. Background of the gene and history off research on it
1. How the function of mutations to the gene has been assessed.

The background information from part 1 will put your focal functional assay paper in context and help you understand its biological background.  

You will produce 2 major outputs

1. A **research paper** on the gene.  The first paper of the paper will be on the basic biology of the gene.  This will set the stage for the second part, which will provide in-depth analysis of your chosen focal paper and its functional assay.  This paper will be written for an audience of your peers who have a similar strong background in biology.
1. An **research presentation** on the gene.  This will take the general form of talk given at a research conference, but be designed for first-year biology students with only a basic background in biology.  After briefly summarizing the background of the gene, you will present details of how the functional assay was conducted and what it revealed.


### Part 0: Select a paper
 

At the beginning of this course the class will be presented with approximately 20 recent papers that present the results functional assays of genes thought to have undergone recent natural selection in humans.  Each of these papers tests the hypothesis that a mutation in a gene is **causally related** to phenotypic differences between human populations.  Each member of the class will  select one of the studies to be their focal paper and gene for the duration of the class.

### Part 1: Know your history

Your next task will be to research the basic biology of the gene and outline of the history of the gene.  To answer the questions listed below you will use resources compiled by bioinformatics, such as the Protein Databank and GeneCards, medical geneticists (Mendellian Inheritance in Man), as well as the primary literature.  This list of questions below is long, but a single resource will often yield answers to multiple questions.

Basic biological questions you will try to answer include

* **Basic molecular biology**: What chromosome is the gene located on?  How big is the gene? How many introns?  Does it undergo alternative splicing?  It is part of a larger family of genes?  What other organisms does it occur in?  
* **Basic biochemistry and cell biology:** What type of molecular product does it produce?  Does it have the same function in all organisms and cells, or does it have multiple functions? What tissues is it expressed in? Has the 3D structure of the molecular product been determined?
* **Phenotypes associated with the gene**: What organism trait is the gene associated with (e.g. skin pigmentation, oxygen absorption, arsenic metabolism)?  Are mutations in the gene associated with any diseases such as cancer?  Does it follow simple Mendelian inheritance patterns?

Once you have a handle on the basic biology of the gene you will create a timeline of the research conducted on the gene, paying particular attention to how the gene was flagged for evolutionary studies of local human adaption.  Question you will try to answer include:

* **Discovery**: When was the gene first discovered and named?  Has laboratory or medical biologists know about it for a long time, or was it first identified after the human genome was sequenced/
* **Model organisms**: What model organisms have been used to study the gene, and was the gene identified in them before humans?  For example, the gene Shroom studied by the Hildebrand lab at Pitt was first identified but mis-characterized in frogs.  Jeff Hildebrand re-discovered it in mice, and demonstrated it occurs in humans.  He has since worked on the gene extensively in fruit flies.
* **Genomic analysis**: When approximately did computational biologists first find evidence for the gene being under recent natural selection?  Was it during a broad-scale scan of the entire genome, or where they already interested in this gene?

Finally, you will try to determine when the phenotype that is now associated with this gene was first thought to show adaptive variation.  For example, since before Darwin researchers have proposed that variation in pigmentation was adaptive for protection against the harmful effects of the song.  In contrast, it has only relatively recently been hypothesized that skin lightening is adaptively associated with vitamin D synthesis in regions with less sunlight.

### Part 2: Functional assay dissection

The second part of your research will be to dissect your focal paper to determine the logic of the functional assay being conducted.  Most lab research papers in biology utilize multiple molecular, biochemical, cellular and/or physiological methods and carry out multiple sub-experiment.  Your goal will be to understand how the different parts of the paper relate to each other, and to what you've learned about the biology of your focal gene.

Questions you will address include:

* What is the hypothesis being tested in the study, and what is the **causal pathway** between mutations and phenotypes?  How can this hypothesis and these connections be most succinctly summarized?
* Which 1 or 2 experiments provide the most compelling evidence for the functional significance of the gene?  Which graphs present the results for these experiments?
* How clear are the results presented, and what can be done to make them clearer?
* Which methods were most relevant to producing these results?
* How can these methods be best summarized to communicate them to an audience of non-specialists?
* How well do these results address the focal hypothesis?  Are you satisfied with the conclusions of the authors?
* What experiments should be done next?
