# E-mail

E-mail will be used routinely in this class for communication.  I will usually send out e-mail notices using the University e-mail addresses available through Canvas.  Such notices are also posted as Announcements on Canvas.  

## University Email Policy

Each student is issued a University e-mail address (username@pitt.edu) upon admittance.  This e-mail address may be used by the University for official communication with students.  Students are expected to read e-mail sent to this account on a regular basis.  Failure to read and react to University communications in a timely manner does not absolve the student from knowing and complying with the content of the communications.  The University provides an e-mail forwarding service that allows students to read their e-mail via other service providers (e.g. Gmail).  Students that choose to forward their e-mail from their pitt.edu address to another address do so at their own risk.  If e-mail is lost as a result of forwarding, it does not absolve the student from responding to official communications sent to their University e-mail address.  To forward e-mail sent to your University account, go to http://accounts.pitt.edu, log into your account, click on ‘Edit Forwarding Addresses’, and follow the instructions on the page.  Be sure to log out of your account when you have finished.


